version: '3'
services:
  backend:
    # ?? ??????? Dockerfile? ???? Docker ???? ??
    build: .
    # ???? 8112 ??? ????? 80 ??? ??
    ports:
      - "8112:80"
    # ????? ??
    container_name: spring-recipick-green
    environment:
      - TZ=Asia/Seoul
    networks:
      - servernetwork

networks:
  servernetwork:
    external: true
    driver: bridge